application:
  title: Easy Inteview
  version: 0.0.1

server.servlet.context-path: /api

# swagger 3 issue
spring.mvc.pathmatch.matching-strategy: ant_path_matcher

# datasource
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=create schema if not exists EASY_INTERVIEW
    username: sa
    dbcp2:
      validation-query: SELECT 'Hello' from DUAL
    hikari:
      maximum-pool-size: 25
      minimum-idle: 25
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 180000
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: true

# logging
logging:
  level:
    web: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE
